name: main

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap
        run: npm ci

      - name: Test
        run: npm test

      - name: Prepare
        run: npx playwright install

      - name: Build
        run: npm run build
