name: main

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "*.md"
      - "/integration/*"
      - "package*.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Bootstrap
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
