name: main

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 23.x
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: "npm"

      - name: Bootstrap
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
